<?php
use Illuminate\Support\Facades\URL;

if(strpos(URL::current(), 'politics.html'))
{
    header("Location: /page/terms-sale");
    exit;
}

if(strpos(URL::current(), '/page/terms-sale'))
{
    header("Location: /condition");
    exit;
}

Route::get('/page/faq', function(){ return Redirect::to('/faq', 301); });
Route::get('/de/page/faq', function(){ return Redirect::to('/de/faq', 301); });
Route::get('/ee/page/faq', function(){ return Redirect::to('/ee/faq', 301); });
Route::get('/en/page/faq', function(){ return Redirect::to('/en/faq', 301); });
Route::get('/pl/page/faq', function(){ return Redirect::to('/pl/faq', 301); });
Route::get('/lt/page/faq', function(){ return Redirect::to('/lt/faq', 301); });
Route::get('/lv/page/faq', function(){ return Redirect::to('/lv/faq', 301); });
Route::get('/ru/page/faq', function(){ return Redirect::to('/ru/faq', 301); });
Route::get('/canvas', function(){ return Redirect::to('/new/canvas', 301); });
Route::get('/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/graphic-portrait/classic-portrait', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/lv/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lv/graphic-portrait/classic-portrait', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lv/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/lv/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lv/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/lv/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/lv/new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/lt/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lt/graphic-portrait/classic-portrait', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lt/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/lt/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lt/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/lt/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/lt/new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/pl/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/pl/graphic-portrait/classic-portrait', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/pl/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/pl/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/pl/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/pl/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/pl//new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/de/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/de/graphic-portrait/classic-portrait', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/de/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/de/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/de/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/de/new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/en/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/en/graphic-portrait/classic-portrait', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/en/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/en/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/en/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/en/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/en/new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/ee/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ee/graphic-portrait/classic-portrait', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ee/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/ee/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ee/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/ee/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/ee/new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/ru/graphic-portrait/portrait-beauty-art', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ru/graphic-portrait/classic-portrait', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/graphic-portrait/portrait-dream-art', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ru/graphic-portrait/pop-art-portrait', function(){ return Redirect::to('/ru/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ru/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/ru/graphic-portrait/graphic-portrait', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/ru/new/graphic-portrait/Grafik-Porträt', 301); });
Route::get('/new/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/new/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ee/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/en/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/pl/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/lp/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lt/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lv/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ru/graphic-portrait/dream-art-portrait', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/new/caricature', 301); });
Route::get('/de/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/de/new/caricature', 301); });
Route::get('/ee/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/ee/new/caricature', 301); });
Route::get('/en/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/en/new/caricature', 301); });
Route::get('/pl/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/lp/new/caricature', 301); });
Route::get('/lt/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/lt/new/caricature', 301); });
Route::get('/lv/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/lv/new/caricature', 301); });
Route::get('/ru/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/ru/new/caricature', 301); });
Route::get('/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/new/graphic-portrait/pet-portrait', 301); });
Route::get('/de/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/de/new/graphic-portrait/pet-portrait', 301); });
Route::get('/ee/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/ee/new/graphic-portrait/pet-portrait', 301); });
Route::get('/en/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/en/new/graphic-portrait/pet-portrait', 301); });
Route::get('/pl/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/lp/new/graphic-portrait/pet-portrait', 301); });
Route::get('/lt/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/lt/new/graphic-portrait/pet-portrait', 301); });
Route::get('/lv/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/lv/new/graphic-portrait/pet-portrait', 301); });
Route::get('/ru/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/ru/new/graphic-portrait/pet-portrait', 301); });
Route::get('/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/lp/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/de/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ee/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/en/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/pl/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/lp/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lt/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lv/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ru/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ee/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/en/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/pl/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/lp/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lt/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lv/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ru/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-dream-art', 301); });

Route::get('/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/de/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/de/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ee/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/ee/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/en/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/en/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/pl/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/lp/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lt/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/lt/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lv/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/lv/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ru/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/ru/new/graphic-portrait/pop-art-portrait', 301); });

Route::get('/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/new/graphic-portrait/kartiny', 301); });
Route::get('/de/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/de/new/graphic-portrait/kartiny', 301); });
Route::get('/ee/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/ee/new/graphic-portrait/kartiny', 301); });
Route::get('/en/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/en/new/graphic-portrait/kartiny', 301); });
Route::get('/pl/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/lp/new/graphic-portrait/kartiny', 301); });
Route::get('/lt/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/lt/new/graphic-portrait/kartiny', 301); });
Route::get('/lv/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/lv/new/graphic-portrait/kartiny', 301); });
Route::get('/ru/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/ru/new/graphic-portrait/kartiny', 301); });
Route::get('/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/lp/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });
Route::get('/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/simpsons', 301); });
Route::get('/de/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/de/simpsons', 301); });
Route::get('/ee/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/ee/simpsons', 301); });
Route::get('/en/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/en/simpsons', 301); });
Route::get('/pl/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/lp/simpsons', 301); });
Route::get('/lt/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/lt/simpsons', 301); });
Route::get('/lv/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/lv/simpsons', 301); });
Route::get('/ru/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/ru/simpsons', 301); });
Route::get('/photo', function(){ return Redirect::to('/photo_portrait', 301); });
Route::get('/de/photo', function(){ return Redirect::to('/de/photo_portrait', 301); });
Route::get('/ee/photo', function(){ return Redirect::to('/ee/photo_portrait', 301); });
Route::get('/en/photo', function(){ return Redirect::to('/en/photo_portrait', 301); });
Route::get('/pl/photo', function(){ return Redirect::to('/lp/photo_portrait', 301); });
Route::get('/lt/photo', function(){ return Redirect::to('/lt/photo_portrait', 301); });
Route::get('/lv/photo', function(){ return Redirect::to('/lv/photo_portrait', 301); });
Route::get('/ru/photo', function(){ return Redirect::to('/ru/photo_portrait', 301); });
Route::get('/gallery/oil-pictures', function(){ return Redirect::to('/new/graphic-portrait/kartiny', 301); });
Route::get('/de/gallery/oil-pictures', function(){ return Redirect::to('/de/new/graphic-portrait/kartiny', 301); });
Route::get('/ee/gallery/oil-pictures', function(){ return Redirect::to('/ee/new/graphic-portrait/kartiny', 301); });
Route::get('/en/gallery/oil-pictures', function(){ return Redirect::to('/en/new/graphic-portrait/kartiny', 301); });
Route::get('/pl/gallery/oil-pictures', function(){ return Redirect::to('/pl/new/graphic-portrait/kartiny', 301); });
Route::get('/lt/gallery/oil-pictures', function(){ return Redirect::to('/lt/new/graphic-portrait/kartiny', 301); });
Route::get('/lv/gallery/oil-pictures', function(){ return Redirect::to('/lv/new/graphic-portrait/kartiny', 301); });
Route::get('/ru/gallery/oil-pictures', function(){ return Redirect::to('/ru/new/graphic-portrait/kartiny', 301); });
Route::get('/oil-portrait', function(){ return Redirect::to('/new/graphic-portrait/kartiny', 301); });
Route::get('/de/oil-portrait', function(){ return Redirect::to('/de/new/graphic-portrait/kartiny', 301); });
Route::get('/ee/oil-portrait', function(){ return Redirect::to('/ee/new/graphic-portrait/kartiny', 301); });
Route::get('/en/oil-portrait', function(){ return Redirect::to('/en/new/graphic-portrait/kartiny', 301); });
Route::get('/pl/oil-portrait', function(){ return Redirect::to('/lp/new/graphic-portrait/kartiny', 301); });
Route::get('/lt/oil-portrait', function(){ return Redirect::to('/lt/new/graphic-portrait/kartiny', 301); });
Route::get('/lv/oil-portrait', function(){ return Redirect::to('/lv/new/graphic-portrait/kartiny', 301); });
Route::get('/ru/oil-portrait', function(){ return Redirect::to('/ru/new/graphic-portrait/kartiny', 301); });
Route::get('/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lv/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lv/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/lv/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lv/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/lv/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lt/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lt/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/lt/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lt/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/lt/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/pl/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/pl/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/pl/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/pl/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/pl/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/de/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/de/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/de/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/de/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/en/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/en/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/en/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/en/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/en/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ee/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ee/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/ee/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ee/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/ee/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/graphic-portrait/portrait-beauty-art/buy', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ru/graphic-portrait/classic-portrait/buy', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/graphic-portrait/portrait-dream-art/buy', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ru/graphic-portrait/pop-art-portrait/buy', function(){ return Redirect::to('/ru/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ru/graphic-portrait/portrait-caricature/buy', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-caricature', 301); });
Route::get('/ru/graphic-portrait/graphic-portrait/buy', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/new/caricature', 301); });
Route::get('/de/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/de/new/caricature', 301); });
Route::get('/ee/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/ee/new/caricature', 301); });
Route::get('/en/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/en/new/caricature', 301); });
Route::get('/pl/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/lp/new/caricature', 301); });
Route::get('/lt/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/lt/new/caricature', 301); });
Route::get('/lv/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/lv/new/caricature', 301); });
Route::get('/ru/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/ru/new/caricature', 301); });
Route::get('/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/new/caricature', 301); });
Route::get('/de/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/de/new/caricature', 301); });
Route::get('/ee/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/ee/new/caricature', 301); });
Route::get('/en/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/en/new/caricature', 301); });
Route::get('/pl/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/lp/new/caricature', 301); });
Route::get('/lt/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/lt/new/caricature', 301); });
Route::get('/lv/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/lv/new/caricature', 301); });
Route::get('/ru/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/ru/new/caricature', 301); });
// -------------- графический портрет. новые редиректы ------------------
Route::get('/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/simpsons', 301); });
Route::get('/en/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/en/simpsons', 301); });
Route::get('/pl/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/pl/simpsons', 301); });
Route::get('/lv/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/lv/simpsons', 301); });
Route::get('/lt/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/lt/simpsons', 301); });
Route::get('/ee/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/ee/simpsons', 301); });
Route::get('/de/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/de/simpsons', 301); });
Route::get('/ru/new/graphic-portrait/simpsons-portrait', function(){ return Redirect::to('/ru/simpsons', 301); });

Route::get('/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/simpsons', 301); });
Route::get('/en/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/en/simpsons', 301); });
Route::get('/pl/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/pl/simpsons', 301); });
Route::get('/lv/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/lv/simpsons', 301); });
Route::get('/lt/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/lt/simpsons', 301); });
Route::get('/ee/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/ee/simpsons', 301); });
Route::get('/de/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/de/simpsons', 301); });
Route::get('/ru/new/graphic-portrait/simposons-custums', function(){ return Redirect::to('/ru/simpsons', 301); });

Route::get('/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/new/graphic-portrait/customs-royal-portraits', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });

Route::get('/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/new/graphic-portrait/pet-portrait', 301); });
Route::get('/en/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/en/new/graphic-portrait/pet-portrait', 301); });
Route::get('/pl/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/pl/new/graphic-portrait/pet-portrait', 301); });
Route::get('/lv/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/lv/new/graphic-portrait/pet-portrait', 301); });
Route::get('/lt/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/lt/new/graphic-portrait/pet-portrait', 301); });
Route::get('/ee/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/ee/new/graphic-portrait/pet-portrait', 301); });
Route::get('/de/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/de/new/graphic-portrait/pet-portrait', 301); });
Route::get('/ru/new/graphic-portrait/spanpetspanportrait', function(){ return Redirect::to('/ru/new/graphic-portrait/pet-portrait', 301); });

Route::get('/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/new/graphic-portrait/kartiny', 301); });
Route::get('/en/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/en/new/graphic-portrait/kartiny', 301); });
Route::get('/pl/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/pl/new/graphic-portrait/kartiny', 301); });
Route::get('/lv/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/lv/new/graphic-portrait/kartiny', 301); });
Route::get('/lt/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/lt/new/graphic-portrait/kartiny', 301); });
Route::get('/ee/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/ee/new/graphic-portrait/kartiny', 301); });
Route::get('/de/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/de/new/graphic-portrait/kartiny', 301); });
Route::get('/ru/new/graphic-portrait/spanpaintingsspan', function(){ return Redirect::to('/ru/new/graphic-portrait/kartiny', 301); });

Route::get('/new/graphic-portrait/-988', function(){ return Redirect::to('/new/graphic-portrait/kartiny', 301); });
Route::get('/en/new/graphic-portrait/-988', function(){ return Redirect::to('/en/new/graphic-portrait/kartiny', 301); });
Route::get('/pl/new/graphic-portrait/-988', function(){ return Redirect::to('/pl/new/graphic-portrait/kartiny', 301); });
Route::get('/lv/new/graphic-portrait/-988', function(){ return Redirect::to('/lv/new/graphic-portrait/kartiny', 301); });
Route::get('/lt/new/graphic-portrait/-988', function(){ return Redirect::to('/lt/new/graphic-portrait/kartiny', 301); });
Route::get('/ee/new/graphic-portrait/-988', function(){ return Redirect::to('/ee/new/graphic-portrait/kartiny', 301); });
Route::get('/de/new/graphic-portrait/-988', function(){ return Redirect::to('/de/new/graphic-portrait/kartiny', 301); });
Route::get('/ru/new/graphic-portrait/-988', function(){ return Redirect::to('/ru/new/graphic-portrait/kartiny', 301); });

Route::get('/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/new/caricature', 301); });
Route::get('/en/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/en/new/caricature', 301); });
Route::get('/pl/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/pl/new/caricature', 301); });
Route::get('/lv/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/lv/new/caricature', 301); });
Route::get('/lt/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/lt/new/caricature', 301); });
Route::get('/ee/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/ee/new/caricature', 301); });
Route::get('/de/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/de/new/caricature', 301); });
Route::get('/ru/new/graphic-portrait/portrait-spancaricaturespan', function(){ return Redirect::to('/ru/new/caricature', 301); });

Route::get('/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/new/caricature', 301); });
Route::get('/en/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/en/new/caricature', 301); });
Route::get('/pl/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/pl/new/caricature', 301); });
Route::get('/lv/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/lv/new/caricature', 301); });
Route::get('/lt/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/lt/new/caricature', 301); });
Route::get('/ee/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/ee/new/caricature', 301); });
Route::get('/de/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/de/new/caricature', 301); });
Route::get('/ru/new/graphic-portrait/portrait-caricature', function(){ return Redirect::to('/ru/new/caricature', 301); });

Route::get('/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/new/caricature', 301); });
Route::get('/en/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/en/new/caricature', 301); });
Route::get('/pl/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/pl/new/caricature', 301); });
Route::get('/lv/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/lv/new/caricature', 301); });
Route::get('/lt/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/lt/new/caricature', 301); });
Route::get('/ee/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/ee/new/caricature', 301); });
Route::get('/de/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/de/new/caricature', 301); });
Route::get('/ru/new/graphic-portrait/portret-karykatura', function(){ return Redirect::to('/ru/new/caricature', 301); });

Route::get('/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/new/caricature', 301); });
Route::get('/en/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/en/new/caricature', 301); });
Route::get('/pl/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/pl/new/caricature', 301); });
Route::get('/lv/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/lv/new/caricature', 301); });
Route::get('/lt/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/lt/new/caricature', 301); });
Route::get('/ee/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/ee/new/caricature', 301); });
Route::get('/de/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/de/new/caricature', 301); });
Route::get('/ru/new/graphic-portrait/karikatur-porträt', function(){ return Redirect::to('/ru/new/caricature', 301); });

Route::get('/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/en/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/en/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/pl/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/pl/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lv/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/lv/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lt/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/lt/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ee/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/ee/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/de/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/de/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ru/new/graphic-portrait/portrait-pop-art', function(){ return Redirect::to('/ru/new/graphic-portrait/pop-art-portrait', 301); });

Route::get('/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/en/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/en/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/pl/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/pl/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lv/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/lv/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/lt/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/lt/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ee/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/ee/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/de/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/de/new/graphic-portrait/pop-art-portrait', 301); });
Route::get('/ru/graphic-portrait/portret-pop-art', function(){ return Redirect::to('/ru/new/graphic-portrait/pop-art-portrait', 301); });

Route::get('/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/new/graphic-portrait/portrait-spanclassicspan', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });

Route::get('/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/new/graphic-portrait/classic-portrait', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });

Route::get('/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/new/graphic-portrait/portret-graficzny', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });

Route::get('/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/new/graphic-portrait/klasisks-portrets', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });

Route::get('/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/en/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/en/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/pl/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/pl/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lv/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/lv/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/lt/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/lt/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ee/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/ee/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/de/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/de/new/graphic-portrait/graphic-portrait', 301); });
Route::get('/ru/new/graphic-portrait/Grafik-Porträt', function(){ return Redirect::to('/ru/new/graphic-portrait/graphic-portrait', 301); });

Route::get('/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/en/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/pl/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lv/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lt/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ee/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/de/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ru/new/graphic-portrait/spanbeauty-art-span-portree', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-beauty-art', 301); });

Route::get('/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/en/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/pl/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lv/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lt/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ee/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/de/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ru/new/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-beauty-art', 301); });

Route::get('/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/en/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/pl/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lv/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lt/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ee/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/de/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ru/new/graphic-portrait/süßes Kunstportrait', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-beauty-art', 301); });

Route::get('/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/en/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/pl/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lv/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/lt/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ee/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/de/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-beauty-art', 301); });
Route::get('/ru/graphic-portrait/portret-beauty-art', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-beauty-art', 301); });

Route::get('/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/en/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/pl/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lv/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lt/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ee/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ru/new/graphic-portrait/spanartspan-portraits', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-dream-art', 301); });

Route::get('/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/en/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/pl/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lv/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lt/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ee/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ru/new/graphic-portrait/portret-dream-art', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-dream-art', 301); });

Route::get('/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/en/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/pl/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lv/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/lt/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ee/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/de/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-dream-art', 301); });
Route::get('/ru/new/graphic-portrait/traum-kunst-porträt', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-dream-art', 301); });

Route::get('/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/new/caricature/caricature-for-birthday', 301); });
Route::get('/en/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/en/new/caricature/caricature-for-birthday', 301); });
Route::get('/pl/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/pl/new/caricature/caricature-for-birthday', 301); });
Route::get('/lv/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/lv/new/caricature/caricature-for-birthday', 301); });
Route::get('/lt/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/lt/new/caricature/caricature-for-birthday', 301); });
Route::get('/ee/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/ee/new/caricature/caricature-for-birthday', 301); });
Route::get('/de/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/de/new/caricature/caricature-for-birthday', 301); });
Route::get('/ru/new/caricature/spancaricaturespan-for-birthday', function(){ return Redirect::to('/ru/new/caricature/caricature-for-birthday', 301); });

Route::get('/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/new/caricature/caricature-for-birthday', 301); });
Route::get('/en/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/en/new/caricature/caricature-for-birthday', 301); });
Route::get('/pl/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/pl/new/caricature/caricature-for-birthday', 301); });
Route::get('/lv/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/lv/new/caricature/caricature-for-birthday', 301); });
Route::get('/lt/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/lt/new/caricature/caricature-for-birthday', 301); });
Route::get('/ee/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/ee/new/caricature/caricature-for-birthday', 301); });
Route::get('/de/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/de/new/caricature/caricature-for-birthday', 301); });
Route::get('/ru/new/caricature/caricature_for_birthday', function(){ return Redirect::to('/ru/new/caricature/caricature-for-birthday', 301); });

Route::get('/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/new/caricature/caricature-for-colleagues', 301); });
Route::get('/en/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/en/new/caricature/caricature-for-colleagues', 301); });
Route::get('/pl/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/pl/new/caricature/caricature-for-colleagues', 301); });
Route::get('/lv/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/lv/new/caricature/caricature-for-colleagues', 301); });
Route::get('/lt/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/lt/new/caricature/caricature-for-colleagues', 301); });
Route::get('/ee/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/ee/new/caricature/caricature-for-colleagues', 301); });
Route::get('/de/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/de/new/caricature/caricature-for-colleagues', 301); });
Route::get('/ru/new/caricature/сaricature_for_сolleagues', function(){ return Redirect::to('/ru/new/caricature/caricature-for-colleagues', 301); });

Route::get('/new/caricature/wedding_caricature', function(){ return Redirect::to('/new/caricature/wedding-caricature', 301); });
Route::get('/en/new/caricature/wedding_caricature', function(){ return Redirect::to('/en/new/caricature/wedding-caricature', 301); });
Route::get('/pl/new/caricature/wedding_caricature', function(){ return Redirect::to('/pl/new/caricature/wedding-caricature', 301); });
Route::get('/lv/new/caricature/wedding_caricature', function(){ return Redirect::to('/lv/new/caricature/wedding-caricature', 301); });
Route::get('/lt/new/caricature/wedding_caricature', function(){ return Redirect::to('/lt/new/caricature/wedding-caricature', 301); });
Route::get('/ee/new/caricature/wedding_caricature', function(){ return Redirect::to('/ee/new/caricature/wedding-caricature', 301); });
Route::get('/de/new/caricature/wedding_caricature', function(){ return Redirect::to('/de/new/caricature/wedding-caricature', 301); });
Route::get('/ru/new/caricature/wedding_caricature', function(){ return Redirect::to('/ru/new/caricature/wedding-caricature', 301); });

Route::get('/new/caricature/family_caricature', function(){ return Redirect::to('/new/caricature/family-caricature', 301); });
Route::get('/en/new/caricature/family_caricature', function(){ return Redirect::to('/en/new/caricature/family-caricature', 301); });
Route::get('/pl/new/caricature/family_caricature', function(){ return Redirect::to('/pl/new/caricature/family-caricature', 301); });
Route::get('/lv/new/caricature/family_caricature', function(){ return Redirect::to('/lv/new/caricature/family-caricature', 301); });
Route::get('/lt/new/caricature/family_caricature', function(){ return Redirect::to('/lt/new/caricature/family-caricature', 301); });
Route::get('/ee/new/caricature/family_caricature', function(){ return Redirect::to('/ee/new/caricature/family-caricature', 301); });
Route::get('/de/new/caricature/family_caricature', function(){ return Redirect::to('/de/new/caricature/family-caricature', 301); });
Route::get('/ru/new/caricature/family_caricature', function(){ return Redirect::to('/ru/new/caricature/family-caricature', 301); });

Route::get('/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/new/caricature/black-and-white-caricatures', 301); });
Route::get('/en/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/en/new/caricature/black-and-white-caricatures', 301); });
Route::get('/pl/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/pl/new/caricature/black-and-white-caricatures', 301); });
Route::get('/lv/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/lv/new/caricature/black-and-white-caricatures', 301); });
Route::get('/lt/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/lt/new/caricature/black-and-white-caricatures', 301); });
Route::get('/ee/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/ee/new/caricature/black-and-white-caricatures', 301); });
Route::get('/de/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/de/new/caricature/black-and-white-caricatures', 301); });
Route::get('/ru/new/caricature/black_and_white_caricatures', function(){ return Redirect::to('/ru/new/caricature/black-and-white-caricatures', 301); });

Route::get('/new/caricature/athlete_caricatures', function(){ return Redirect::to('/new/caricature/athlete-caricatures', 301); });
Route::get('/en/new/caricature/athlete_caricatures', function(){ return Redirect::to('/en/new/caricature/athlete-caricatures', 301); });
Route::get('/pl/new/caricature/athlete_caricatures', function(){ return Redirect::to('/pl/new/caricature/athlete-caricatures', 301); });
Route::get('/lv/new/caricature/athlete_caricatures', function(){ return Redirect::to('/lv/new/caricature/athlete-caricatures', 301); });
Route::get('/lt/new/caricature/athlete_caricatures', function(){ return Redirect::to('/lt/new/caricature/athlete-caricatures', 301); });
Route::get('/ee/new/caricature/athlete_caricatures', function(){ return Redirect::to('/ee/new/caricature/athlete-caricatures', 301); });
Route::get('/de/new/caricature/athlete_caricatures', function(){ return Redirect::to('/de/new/caricature/athlete-caricatures', 301); });
Route::get('/ru/new/caricature/athlete_caricatures', function(){ return Redirect::to('/ru/new/caricature/athlete-caricatures', 301); });

Route::get('/new/caricature/group_caricatures', function(){ return Redirect::to('/new/caricature/group-caricatures', 301); });
Route::get('/en/new/caricature/group_caricatures', function(){ return Redirect::to('/en/new/caricature/group-caricatures', 301); });
Route::get('/pl/new/caricature/group_caricatures', function(){ return Redirect::to('/pl/new/caricature/group-caricatures', 301); });
Route::get('/lv/new/caricature/group_caricatures', function(){ return Redirect::to('/lv/new/caricature/group-caricatures', 301); });
Route::get('/lt/new/caricature/group_caricatures', function(){ return Redirect::to('/lt/new/caricature/group-caricatures', 301); });
Route::get('/ee/new/caricature/group_caricatures', function(){ return Redirect::to('/ee/new/caricature/group-caricatures', 301); });
Route::get('/de/new/caricature/group_caricatures', function(){ return Redirect::to('/de/new/caricature/group-caricatures', 301); });
Route::get('/ru/new/caricature/group_caricatures', function(){ return Redirect::to('/ru/new/caricature/group-caricatures', 301); });

Route::get('/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });

Route::get('/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/graphic-portrait/portrait-in-image', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });

Route::get('/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/graphic-portrait/portret-stylizowany', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });

Route::get('/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/graphic-portrait/portrait-in-the-image', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });

Route::get('/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/new/caricature/portrait-in-the-image', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });

Route::get('/new/caricature/portrait-in-image', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/new/caricature/portrait-in-image', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/new/caricature/portrait-in-image', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/new/caricature/portrait-in-image', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/new/caricature/portrait-in-image', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/new/caricature/portrait-in-image', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/new/caricature/portrait-in-image', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/new/caricature/portrait-in-image', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });

Route::get('/new/caricature/portret-stylizowany', function(){ return Redirect::to('/new/graphic-portrait/portrait-historical', 301); });
Route::get('/en/new/caricature/portret-stylizowany', function(){ return Redirect::to('/en/new/graphic-portrait/portrait-historical', 301); });
Route::get('/pl/new/caricature/portret-stylizowany', function(){ return Redirect::to('/pl/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lv/new/caricature/portret-stylizowany', function(){ return Redirect::to('/lv/new/graphic-portrait/portrait-historical', 301); });
Route::get('/lt/new/caricature/portret-stylizowany', function(){ return Redirect::to('/lt/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ee/new/caricature/portret-stylizowany', function(){ return Redirect::to('/ee/new/graphic-portrait/portrait-historical', 301); });
Route::get('/de/new/caricature/portret-stylizowany', function(){ return Redirect::to('/de/new/graphic-portrait/portrait-historical', 301); });
Route::get('/ru/new/caricature/portret-stylizowany', function(){ return Redirect::to('/ru/new/graphic-portrait/portrait-historical', 301); });
